image: node:12.14

stages:
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .yarn
    - cache/Cypress
    - node_modules/

before_script:
  - echo "MIDGARD_API_IP:" ${MIDGARD_API_IP}
  - yarn
  - npm i -g firebase-tools
  - firebase -V

test:develop:
  stage: test
  script:
    - yarn test
  environment:
    name: develop

deploy:testnet-staging:
  stage: deploy
  script:
    - firebase use --token ${FIREBASE_TOKEN} bepswap-testnet-staging
    - firebase deploy --token ${FIREBASE_TOKEN}
  environment:
    name: testnet
  only:
    - development
   when: manual

deploy:testnet-production:
  stage: deploy
  script:
    - firebase use --token ${FIREBASE_TOKEN} bepswap-testnet
    - firebase deploy --token ${FIREBASE_TOKEN}
  environment:
    name: testnet
  only:
    - master
  when: manual

deploy:chaosnet-staging:
  stage: deploy
  script:
    - firebase use --token ${FIREBASE_TOKEN} bepswap-chaosnet-staging
    - firebase deploy --token ${FIREBASE_TOKEN}
  environment:
    name: chaosnet
  only:
    - chaosnet-dev
  when: manual

deploy:chaosnet-production:
  stage: deploy
  script:
    - firebase use --token ${FIREBASE_TOKEN} bepswap-app
    - firebase deploy --token ${FIREBASE_TOKEN}
  environment:
    name: chaosnet
  only:
    - chaosnet-prod
  when: manual

deploy:cloudfront:
  stage: deploy
  script:
    - yarn build
    - apt-get update -y && apt install python3-pip -y
    - pip3 install --upgrade pip
    - pip3 install awscli --upgrade
    - make aws-ci-login
    - aws s3 cp --recursive build/ s3://${CLOUDFRONT_BUCKET}
  only:
    - master

# Build docker image
build-docker:
  stage: deploy
  image: docker:stable
  only:
    - master
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add make git jq curl
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build -t registry.gitlab.com/thorchain/bepswap/bepswap-web-ui .
    - docker push registry.gitlab.com/thorchain/bepswap/bepswap-web-ui
